apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresapplication
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Arastusharma/postgres-config.git
    targetRevision: HEAD
    path: Postgres
  destination: 
    server: https://kubernetes.default.svc
    namespace: postgresapplication

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
